### ISSUE TITLE
Separate Package for ResponderAcceptsInterface?

### ISSUE THREAD

**Issue by jakejohns** [radarphp/Radar.Adr#14]
Does it make any sense to make a separate package for
Radar\Adr\Responder\ResponderAcceptsInterface ?

Similar to what is done in Aura\Payload?

This way we can build components which are compatible but do not have a
dependency on the entirety of radar/adr.

**Comment by pmjones** [comment]
/me thinks

You know, it just might. I wonder if it would be a Radar\Responder_Interface package, or something else that goes in Aura instead?
