### ISSUE TITLE
Service level actions?

### ISSUE THREAD

**Issue by jakejohns** [radarphp/Radar.Adr#29]
Am I off in wanting to be able to use 'service' level objects from the container as actions in some cases?

This would allow me, for example, to have two domains which have considerably similar logic to use the same class for the actual domain action, but composed of different dependencies as configured.

The resolver currently uses only `InjectionFactory::newInstance` which I believe precludes this.

I feel like I wan to be able to do this, but the following occur to me:
- I'm not sure how one would differentiate between the desire for a service or a class just based on the string, other than bad magical weirdness.
- Maybe it's just always better to have an empty class there extending the base functionality. Meaning, in the example below, instead of using `My\Create` for both `My\Domain` and `My\Other`, I just always need to create empty classes which extend `My\Create`, even if they add no functionality.

Example:

``` php
<?php

abstract class AbstractService
{
    public function  __construct(
        PayloadInterface $payload,
        ValidatorInterface $validator,
        GatewayInterface $gateway
    ) {
        // ...
    }
    // ...
}

class Create extends AbstractService
{
    public function __invoke($data)
    {
        $this->init();

        if (! $this->validator->isValid($data)) {
            return $this->invalid();
        }

        try {
            $entity = $this->gateway->create($data);
        } catch (Exception $e) {
            return $this->error($e);
        }

        return $this->payload->setStatus(Status::SUCCESS)
            ->setOutput($entity);
    }
}


class Config
{
    public function define(Container $di)
    {
        // some domain
        $this->set(
            'my/domain:create',
            $di->lazyNew(
                'My\Create',
                [
                    'validator' => $di->lazyNew('My\Domain\Validator'),
                    'gateway' => $di->lazyNew('My\Domain\Gateway'),
                ]
            )
        );

        // some other, but domain
        $this->set(
            'my/other:create',
            $di->lazyNew(
                'My\Create',
                [
                    'validator' => $di->lazyNew('My\Other\Validator'),
                    'gateway' => $di->lazyNew('My\Other\Gateway'),
                ]
            )
        );
    }

    public function modify(Container $di)
    {
        $adr = $di->get('radar/adr:adr');

        $adr->post('My\Domain\Create', '/domain/create', 'my/domain:create');
        $adr->post('My\Other\Create', '/other/create', 'my/other:create');
    }
}
```

Maybe something like `$adr->post(...)->useService()`, but I think that mucks things up with Arbiter.
Maybe the resolver could check `$di->has()` for a service?
I dunno, I don't think I really like either option. Maybe my desires are unfounded.

Thoughts?

**Comment by pmjones** [comment]
I've been thinking about this, and I can see why you'd want it. Even so, the mention of "optional" dependencies tends to raise a flag for me.

You say:

> Maybe it's just always better to have an empty class there extending the base functionality. Meaning, in the example below, instead of using My\Create for both My\Domain and My\Other, I just always need to create empty classes which extend My\Create, even if they add no functionality.

I think that's the way to go, or at least something similar to it. Maybe the thing to do is create a constructor-less abstract base class, and the subclasses implement the constructor. That would allow you separate classes to set constructor params on, and thus avoid the service.

Does that begin to help?

**Comment by jakejohns** [comment]
long belated response: Yes, that helped. Thanks.

**Comment by pmjones** [comment]
Dude, given my own latency on responses, yours was practically instantaneous. ;-)
